config/routes.rb
Rails.application.routes.draw do
  root 'politicians#index'
  get 'machines/index'
  
  post 'machines/crawl'
  get 'politicians/scraping'

  resources :words
  resources :politicians

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord
    validates :tweet_id, uniqueness: true
end

app/models/politician.rb
class Politician < ApplicationRecord
    
    
    def scraping
        @politicians = Politician.where(switch: "オン")
        puts "#{@politicians.count}"
        config = {
        	:consumer_key => 'HxTbIelBlbjp56cERilNt6XEy',
        	:consumer_secret => 'mzrDSM4WkFC23cx1TRQPrQ4p2AT0Yt1RxYpojAcD5Ua7RZZPWA',
        	:access_token => '732909452563619845-ptSOidEhCvXBPGCWUF6KoOqrFRcJAJ4',
        	:access_token_secret => 'x7m24zjdrJyhe1w8dmt5paIPEgfnSTmrCjLXJ8CnASjQd'
        }
        
        @twClient = Twitter::REST::Client.new(config)
        
        @politicians.each do |politician|
            # word を含む tweet を 10 件取得する
            results = @twClient.search(politician.name, :count => 20, :result_type => "recent")
            results.take(20).each do |tweet|
                begin
                    @machine = Machine.new
                    @machine.tweet_id = tweet[:id]
                    @machine.politician = politician.name
                    @machine.name = "@" + tweet[:user][:screen_name]
                    @machine.text = tweet[:text]
                    @machine.save!
                rescue => e
                      p "エラー"
                end
            end
        end
        
    end
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  require 'twitter'

  def index
    @machines = Machine.all
  end
  
  def crawl
    config = {
    	:consumer_key => 'HxTbIelBlbjp56cERilNt6XEy',
    	:consumer_secret => 'mzrDSM4WkFC23cx1TRQPrQ4p2AT0Yt1RxYpojAcD5Ua7RZZPWA',
    	:access_token => '732909452563619845-ptSOidEhCvXBPGCWUF6KoOqrFRcJAJ4',
    	:access_token_secret => 'x7m24zjdrJyhe1w8dmt5paIPEgfnSTmrCjLXJ8CnASjQd'
    }
    
    twClient = Twitter::REST::Client.new(config)
    
    word1 =  params[:word][:word1]
    word2 =  params[:word][:word2]
    word3 =  params[:word][:word3]
    word_sum = word1 + word2 + word3

    # word を含む tweet を 10 件取得する
    results = twClient.search(word_sum, :count => 100, :result_type => "recent", :include_entities => true)

    results.take(1000).each do |tweet|
      tweet.media.each do |media| #画像付きのツイート取得
        @machine = Machine.new
        @machine.tweet = tweet[:id]
        @machine.name = "@" + tweet[:user][:screen_name]
        @machine.text = tweet[:text]
        @machine.geo = tweet[:coordinates]
        @machine.url = media.media_url
        
        txt = "#{tweet[:text]}" ##　形態素解析
        
        natto = Natto::MeCab.new
        natto.parse(txt) do |n|
          if n.feature.include?("地域") ##　地域が含まれればインスタンスに追加
              puts @machine[:mecab] = "#{n.surface}: #{n.feature}"
          end
        end
        
        if !tweet[:coordinates].nil? || !@machine[:mecab].nil? #位置情報が付いていれば保存
          @machine.save!
        end
        
      end
    end
    
    @mashines = Machine.all

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @word = Word.new
    @mashines = Machine.all
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
    http_basic_authenticate_with name: "seijipress", password: "seijipress"


    def index
      @politicians = Politician.all
      @q        = Politician.search(params[:q])
      @results = @q.result(distinct: true)
    end
    
    def new
        @politician = Politician.new
    end
    
    def create
     @politician = Politician.new(politician_params)
     if @politician.save
       redirect_to root_path
     else
       render 'politicians/new'
     end
    end
    
    def edit
      @politician = Politician.find(params[:id])
    end
    
    def destroy
      @politician = Politician.find(params[:id])
        if @politician.delete
         flash[:success] = "deleted"
        end
        redirect_to root_path
    end
    
    def show
      @politician = Politician.find(params[:id])
      @machines = Machine.where(politician: "#{@politician.name}")
    end
    
    def update
        @politician = Politician.find(params[:id])
        @politician.update(politician_params)
        redirect_to root_path
    end
    
    
    def scraping
        @politicians = Politician.where(switch: "オン")
        puts "#{@politicians.count}"
        config = {
        	:consumer_key => 'HxTbIelBlbjp56cERilNt6XEy',
        	:consumer_secret => 'mzrDSM4WkFC23cx1TRQPrQ4p2AT0Yt1RxYpojAcD5Ua7RZZPWA',
        	:access_token => '732909452563619845-ptSOidEhCvXBPGCWUF6KoOqrFRcJAJ4',
        	:access_token_secret => 'x7m24zjdrJyhe1w8dmt5paIPEgfnSTmrCjLXJ8CnASjQd'
        }
        
        @twClient = Twitter::REST::Client.new(config)
        
        @politicians.each do |politician|
            # word を含む tweet を 10 件取得する
            results = @twClient.search(politician.name, :count => 20, :result_type => "recent")
            results.take(20).each do |tweet|
                begin
                    @machine = Machine.new
                    @machine.tweet_id = tweet[:id]
                    @machine.politician = politician.name
                    @machine.name = "@" + tweet[:user][:screen_name]
                    @machine.text = tweet[:text]
                    @machine.save!
                rescue => e
                      p "エラー"
                end
            end
        end
        
        redirect_to root_path
    end
    
      private
      
        def politician_params
          params.require(:politician).permit(:name, :age, :party, :occupation, :status, :vote, :election, :image, :switch)
        end
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  
  def index
  end


  def show
  end

  def new
  end

  def edit
  end

  def destroy
  end
  
  def crawl
    config = {
    	:consumer_key => 'HxTbIelBlbjp56cERilNt6XEy',
    	:consumer_secret => 'mzrDSM4WkFC23cx1TRQPrQ4p2AT0Yt1RxYpojAcD5Ua7RZZPWA',
    	:access_token => '732909452563619845-ptSOidEhCvXBPGCWUF6KoOqrFRcJAJ4',
    	:access_token_secret => 'x7m24zjdrJyhe1w8dmt5paIPEgfnSTmrCjLXJ8CnASjQd'
    }
    
    client = Twitter::REST::Client.new(config)
    
    @tweets = []
    client.user_timeline('dkfj').each {|tweet|
    	# Tweet時間
    	puts tweet.created_at
    
    	# Tweet本文
    	@tweets = tweet.text
    
    	# Retweet数
    	puts "Retweetされた数 : " + tweet.retweet_count.to_s
    
    	# お気に入りされた数
    	puts "お気に入りされた数 : " + tweet.favorite_count.to_s
    
    	# 位置情報
    	puts "位置情報 : " + tweet.geo if !tweet.geo.nil?
    }
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  
  def create
     @word = Word.new(word_params)
     if @word.save!
       redirect_to root_path
     else
     end
  end
  
  def update
    @word = Word.find(params[:id])
    @word.update(word_params)
    redirect_to @word
  end
  
  def destroy
    @word = Word.find(params[:id])
    if @word.delete
     flash[:success] = "deleted"
    end
    redirect_to root_path
  end
  
      private
      
        def word_params
          params.require(:word).permit(:word1, :word2, :word3)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_header.html.erb
<div class="ui segment">
  <h3 class="ui right aligned header">
    <%= link_to "議員登録", new_politician_path %>
    <%= link_to "Scraping", politicians_scraping_path %>
  </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="//maps.google.com/maps/api/js?key=AIzaSyCJTRSt6Y1boHemq4jID-Ht_Qe2cFslznk"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' if controller.action_name == "index" %>
<%= yield %>


</body>
</html>

app/views/machines/_form.html.erb
<%= form_for @machine, :html => { :class => "form-horizontal machine" } do |f| %>

  <% if @machine.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @machine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date) %>
  </div>
  <div class="form-group">
    <%= f.label :tweet, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tweet, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tweet) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :text, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :text, :class => 'form-control' %>
    </div>
    <%=f.error_span(:text) %>
  </div>
  <div class="form-group">
    <%= f.label :geo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :geo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:geo) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                machines_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/machines/crawl.html.erb
<% @mashines.each do |tweet| %>
   Date:<%= tweet.date %><br>
   <%= "Tweet:" + tweet.tweet %><br>
   <%= "Nama:" + tweet.name %><br>
   <%= "Text:" + tweet.text %><br>
   Geo:<%= tweet.geo %><br>
   Mecab:<%= tweet.mecab %><br>
   <%= image_tag(tweet.url) %><br><br>
<% end %>

app/views/machines/edit.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/index.html.erb
<%= form_for :word, url: machines_crawl_path do |f| %>
  <p>
    <%= f.text_field :word1, class: 'form-control input-sm', style: "width:500px;", :placeholder => "キーワード1" %>
  </p>
 
  <p>
    <%= f.text_area :word2, class: 'form-control input-sm', style: "width:500px;", :placeholder => "キーワード2" %>
  </p>
  
   <p>
    <%= f.text_area :word3, class: 'form-control input-sm', style: "width:500px;", :placeholder => "キーワード3" %>
  </p>

  <p>
    <%= f.submit "crawl", class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/machines/new.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/show.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @machine.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tweet) %>:</strong></dt>
  <dd><%= @machine.tweet %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @machine.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @machine.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:geo) %>:</strong></dt>
  <dd><%= @machine.geo %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              machines_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_machine_path(@machine), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              machine_path(@machine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/pages/index.html.erb
<% @mashines.each do |tweet| %>
   Date:<%= tweet.date %><br>
   <%= "Tweet:" + tweet.tweet %><br>
   <%= "Nama:" + tweet.name %><br>
   <%= "Text:" + tweet.text %><br>
   Geo:<%= tweet.geo %><br>
   <%= image_tag(tweet.url) %><br><br>
<% end %>

<%= form_for(@word,  html: {class: 'ui form'}) do |f| %>
  <div class="field">
    <label>Word1</label>
      <%= f.text_field :word1, class: '' %>
  </div>
  
  <div class="field">
    <label>Word2</label>
      <%= f.text_field :word2, class: '' %>
  </div>
  
  <div class="field">
    <label>Word3</label>
      <%= f.text_field :word3, class: '' %>
  </div>
  
  <div class="actions">
    <%= f.submit "登録", class: 'ui button'%>
  </div>
<% end %>

app/views/politicians/edit.html.erb
<% if @politician.errors.any? %>
  <div class="ui negative message">
  <i class="close icon"></i>
    <% @politician.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column">
        <%= form_for(@politician, html: {class: 'ui form'}) do |f| %>
        <div class="ui raised segment">
            
            <div class="field">
              <label>名前</label>
              <%= f.text_field :name, class: "" %>
            </div>
            
            
            <div class="field">
              <label>年齢</label>
              <%= f.select :age,  options_for_select((1..90).to_a, 60), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
            <div class="field">
              <label>画像</label>
              <%= f.text_field :image, class: "" %>
            </div>
            
            <div class="field">
              <label>党派</label>
              <%= f.select :party,  options_for_select(["自由民主党", "民進党", "公明党", "日本共産党", "日本維新の会", "自由党 ", "社会民主党", "日本のこころ", "沖縄社会大衆党", "新党大地", "無所属", "その他"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
            <div class="field">
              <label>職業</label>
              <%= f.text_field :occupation, class: "" %>
            </div>
            
            <div class="field">
              <label>新/現/元</label>
              <%= f.select :status,  options_for_select(["新", "現", "元"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
            
            <div class="field">
              <label>得票数</label>
              <%= f.text_field :vote, class: "" %>
            </div>
            
            
            <div class="field">
              <label>当落</label>
              <%= f.select :election,  options_for_select(["当選", "落選"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
        
            <div class="field">
              <label>スイッチ</label>
              <%= f.select :switch,  options_for_select(["オン", "オフ"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
          <div class="actions">
            <%= f.submit "登録", class: 'ui button'%>
          </div>
        </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>

app/views/politicians/index.html.erb
<table class="ui celled table">
  <thead>
    <tr>
    <th>ID</th>
    <th>名前</th>
    <th>年齢</th>
    <th>画像</th>
    <th>党派</th>
    <th>職業</th>
    <th>新/現/元</th>
    <th>得票数</th>
    <th>党派</th>
    <th>スイッチ</th>
    <th>管理</th>
    </tr>
 </thead>
  <tbody>
    <% @politicians.each do |politician| %>
        <tr>
         <td ><%= politician.id %></td>
         <td><%= link_to"#{politician.name}", politician, { :target => "_blank"}  %></td>
         <td ><%= politician.age %></td>
         <td ><%= image_tag(politician.image, :size => '50x50') if !politician.image.nil? %></td>
         <td ><%= politician.party %></td>
         <td ><%= politician.occupation %></td>
         <td ><%= politician.status %></td>
         <td ><%= politician.vote %></td>
         <td ><%= politician.election %></td>
         <td >
             <% if politician.switch == "オン" %>
                 <div class="ui primary button"><%= politician.switch %></div>
             <% elsif politician.switch == "オフ" %>
                 <div class="ui button"><%= politician.switch %></div>
             <% end %>
         </td>
         <td>
          <%= link_to "編集", edit_politician_path(politician.id), { :class => "ui olive button" } %>
          <%= link_to "削除", politician, { :class => "ui red button", method: :delete, data: { confirm: "本当に削除してもいいですか？" }} %>
         </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/politicians/new.html.erb
<% if @politician.errors.any? %>
  <div class="ui negative message">
  <i class="close icon"></i>
    <% @politician.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column">
        <%= form_for(@politician, html: {class: 'ui form'}) do |f| %>
        <div class="ui raised segment">
            
            <div class="field">
              <label>名前</label>
              <%= f.text_field :name, class: "" %>
            </div>
            
            
            <div class="field">
              <label>年齢</label>
              <%= f.select :age,  options_for_select((1..90).to_a, 60), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
            <div class="field">
              <label>画像</label>
              <%= f.text_field :image, class: "" %>
            </div>
            
            <div class="field">
              <label>党派</label>
              <%= f.select :party,  options_for_select(["自由民主党", "民進党", "公明党", "日本共産党", "日本維新の会", "自由党 ", "社会民主党", "日本のこころ", "沖縄社会大衆党", "新党大地", "無所属", "その他"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
            <div class="field">
              <label>職業</label>
              <%= f.text_field :occupation, class: "" %>
            </div>
            
            <div class="field">
              <label>新/現/元</label>
              <%= f.select :status,  options_for_select(["新", "現", "元"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
            
            <div class="field">
              <label>得票数</label>
              <%= f.text_field :vote, class: "" %>
            </div>
            
            
            <div class="field">
              <label>当落</label>
              <%= f.select :election,  options_for_select(["当選", "落選"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
        
            <div class="field">
              <label>スイッチ</label>
              <%= f.select :switch,  options_for_select(["オン", "オフ"]), {}, { class: 'ui fluid dropdown' } %>
            </div>
            
          <div class="actions">
            <%= f.submit "登録", class: 'ui button'%>
          </div>
        </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>

app/views/politicians/show.html.erb
<div class="ui two column centered grid">
  <div class="column">
        <table class="ui celled striped table">
          <thead>
            <tr><th colspan="3">
              <%= @politician.name %>
            </th>
          </tr></thead>
          <tbody>
            <tr>
              <td>ID</td>
              <td><%= @politician.id %></td>
            </tr>
            <tr>
              <td class="collapsing">イメージ</td>
              <td><%= image_tag(@politician.image, :class => "ui fluid image") if !@politician.image.nil? %></td>
            </tr>            
            <tr>
              <td>名前</td>
              <td><%= @politician.name %></td>
            </tr>
            <tr>
              <td>年齢</td>
              <td><%= @politician.age %></td>
            </tr>
            <tr>
              <td>党派</td>
              <td><%= @politician.party %></td>
            </tr>
            <tr>
              <td>職業</td>
              <td><%= @politician.occupation %></td>
            </tr>
            <tr>
              <td>新/現/元</td>
              <td><%= @politician.status %></td>
            </tr>
            <tr>
              <td>得票数</td>
              <td><%= @politician.vote %></td>
            </tr>
            <tr>
              <td>当落</td>
              <td><%= @politician.election %></td>
            </tr>            
            <tr>
              <td>スイッチ</td>
              <td><%= @politician.switch %></td>
            </tr>
            </tbody>
        </table>
        <% @machines.each do |tweet| %>
        <div class="ui raised segment">
           tweet_id:<%= tweet.tweet_id %><br>
           Date:<%= tweet.date %><br>
           <%= "Nama:" + tweet.name %><br>
           <%= "Text:" + tweet.text %><br>
           Geo:<%= tweet.geo %><br>
        </div>
        <% end %>
</div>
</div>